version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns:
          - "*"  # Group all updates into a single larger pull request.

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
